FROM nginx:alpine

# Remove a config padrão do Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia a nossa config customizada
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

# Copia todos os arquivos estáticos (HTML e JS) para a pasta do Nginx
COPY *.html /usr/share/nginx/html/
COPY *.js /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
